CREATE TABLE loans (
    loan_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    loan_type VARCHAR2(50),
    loan_amount NUMBER(15,2),
    issue_date DATE DEFAULT SYSDATE,
    due_date DATE,
    status VARCHAR2(50),
    CONSTRAINT fk_loan_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);