CREATE TABLE audit_logs (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER,
    action VARCHAR2(255),
    action_date DATE DEFAULT SYSDATE,
    ip_address VARCHAR2(50),
    CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);