CREATE TABLE users (
	user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    account_status VARCHAR2(20) DEFAULT 'ACTIVE',
    login_attempts NUMBER DEFAULT 0,
    created_date DATE DEFAULT SYSDATE,
    last_login_date DATE,
    phone_number VARCHAR2(20), -- Kept as VARCHAR2 for flexibility
    address VARCHAR2(255),
    first_name VARCHAR2(50),
    last_name VARCHAR2(50)
);