CREATE TABLE accounts (
    account_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               NUMBER NOT NULL,
    account_number        VARCHAR2(20) UNIQUE NOT NULL,
    account_type          VARCHAR2(50),
    balance               NUMBER(15,2) DEFAULT 0,
    created_date          DATE DEFAULT SYSDATE,
    status                VARCHAR2(20),
    last_transaction_date DATE,
    currency              VARCHAR2(3),
    branch_code           VARCHAR2(10),
    account_status        VARCHAR2(50),
    account_purpose       VARCHAR2(100) NOT NULL,
    CONSTRAINT fk_account_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);