CREATE TABLE fund_transfers (
    transfer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_account VARCHAR2(20),
    to_account VARCHAR2(20),
    amount NUMBER(15,2),
    transfer_date DATE DEFAULT SYSDATE,
    description VARCHAR2(255)
);