CREATE TABLE transactions (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id NUMBER,
    transaction_type VARCHAR2(50),
    amount NUMBER(15,2),
    transaction_date DATE DEFAULT SYSDATE,
    description VARCHAR2(255),
    CONSTRAINT fk_transaction_account FOREIGN KEY (account_id) REFERENCES account(account_id)
);