CREATE TABLE cards (
    card_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id NUMBER NOT NULL,
    card_number VARCHAR2(16) UNIQUE NOT NULL,
    expiry_date DATE,
    cvv VARCHAR2(5),
    card_type VARCHAR2(50),
    issued_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_card_account FOREIGN KEY (account_id) REFERENCES account(account_id)
);