CREATE TABLE beneficiaries (
    beneficiary_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    name VARCHAR2(100),
    account_number VARCHAR2(20),
    bank_name VARCHAR2(100),
    ifsc_code VARCHAR2(20),
    CONSTRAINT fk_beneficiary_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);