CREATE TABLE bill_payments (
    payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER,
    biller_name VARCHAR2(100),
    account_number VARCHAR2(20),
    amount NUMBER(15,2),
    payment_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_bill_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);